#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────
# OpenMono.ai — Set up frp client on the inference box.
# Connects outbound to an OpenMonoAgent Relay instance so the agent box can
# reach this machine's llama-server without port forwarding. Also
# generates a fresh LLAMA_API_KEY for defense-in-depth.
#
# Prerequisites: you must have signed up at your relay first
# (POST /api/signup + /api/signup/activate). Have the response handy:
#
#   {
#     "relayToken":  "omr_...",
#     "remotePort":  12345,
#     "proxyPrefix": "u1a2b3c4d-",
#     "frpsAddress": "relay.openmonoagent.ai",
#     "frpsPort":    7000
#   }
# ─────────────────────────────────────────────────────────────────────

FRP_VERSION="${FRP_VERSION:-0.61.0}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$REPO_DIR/docker/.env"

RED=$'\033[0;31m'
GREEN=$'\033[0;32m'
YELLOW=$'\033[1;33m'
BLUE=$'\033[38;2;163;255;102m'
NC=$'\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── Prerequisite checks ──────────────────────────────────────────────

if [[ $EUID -ne 0 ]] && ! command -v sudo &>/dev/null; then
    err "Must run as root or have sudo installed."
    exit 1
fi

for cmd in curl tar openssl systemctl; do
    if ! command -v "$cmd" &>/dev/null; then
        err "Missing required command: $cmd"
        exit 1
    fi
done

# ── Gather relay signup values ───────────────────────────────────────

FRPS_ADDRESS="${RELAY_FRPS_ADDRESS:-}"
FRPS_PORT="${RELAY_FRPS_PORT:-7000}"
RELAY_TOKEN="${RELAY_TOKEN:-}"
REMOTE_PORT="${RELAY_REMOTE_PORT:-}"
PROXY_PREFIX="${RELAY_PROXY_PREFIX:-}"

if [[ -z "$FRPS_ADDRESS" ]]; then
    read -rp "Relay frpsAddress (e.g. relay.openmonoagent.ai): " FRPS_ADDRESS
fi
if [[ -z "$RELAY_TOKEN" ]]; then
    read -rp "Your relayToken (omr_…):                         " RELAY_TOKEN
fi
if [[ -z "$REMOTE_PORT" ]]; then
    read -rp "Your allocated remotePort:                       " REMOTE_PORT
fi
if [[ -z "$PROXY_PREFIX" ]]; then
    read -rp "Your proxy-name prefix (e.g. u1a2b3c4d-):        " PROXY_PREFIX
fi

if [[ -z "$FRPS_ADDRESS" || -z "$RELAY_TOKEN" || -z "$REMOTE_PORT" || -z "$PROXY_PREFIX" ]]; then
    err "All four relay values are required (frpsAddress, relayToken, remotePort, proxyPrefix)."
    exit 1
fi

if ! [[ "$RELAY_TOKEN" =~ ^omr_ ]]; then
    warn "relayToken does not start with 'omr_' — double-check you copied the activation response."
fi
if ! [[ "$REMOTE_PORT" =~ ^[0-9]+$ ]]; then
    err "remotePort must be numeric (got: $REMOTE_PORT)"
    exit 1
fi

# ── Generate a fresh API key for llama-server ────────────────────────

LLAMA_API_KEY="$(openssl rand -hex 24)"

# ── Detect architecture ──────────────────────────────────────────────

case "$(uname -m)" in
    aarch64) ARCH="arm64" ;;
    x86_64)  ARCH="amd64" ;;
    *) err "Unsupported architecture: $(uname -m)"; exit 1 ;;
esac

info "Detected arch: linux_$ARCH"

# ── Download and install frpc ────────────────────────────────────────

TMP="$(mktemp -d)"
trap "rm -rf $TMP" EXIT

info "Downloading frp v$FRP_VERSION..."
curl -fL \
    "https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/frp_${FRP_VERSION}_linux_${ARCH}.tar.gz" \
    -o "$TMP/frp.tar.gz"

tar xz -C "$TMP" --strip-components=1 -f "$TMP/frp.tar.gz"
sudo install -m 0755 "$TMP/frpc" /usr/local/bin/frpc
ok "Installed /usr/local/bin/frpc"

# ── Write frpc.toml ──────────────────────────────────────────────────

sudo mkdir -p /etc/frp
sudo tee /etc/frp/frpc.toml > /dev/null <<EOF
# frp client — OpenMono.ai inference-box side
# Generated by setup-tunnel-inference.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

serverAddr = "$FRPS_ADDRESS"
serverPort = $FRPS_PORT

# Relay token validated by OpenMono.Relay's HTTP plugin on every Login
# and NewProxy event. Frps itself runs with no shared token.
metadatas.token = "$RELAY_TOKEN"

transport.tls.enable = true

log.to    = "console"
log.level = "info"

[[proxies]]
name              = "${PROXY_PREFIX}llama"
type              = "tcp"
localIP           = "127.0.0.1"
localPort         = 7474
remotePort        = $REMOTE_PORT
metadatas.token   = "$RELAY_TOKEN"
EOF
sudo chmod 0600 /etc/frp/frpc.toml
ok "Wrote /etc/frp/frpc.toml"

# ── Store LLAMA_API_KEY in docker-compose .env ───────────────────────

mkdir -p "$(dirname "$ENV_FILE")"
touch "$ENV_FILE"

# Remove any existing LLAMA_API_KEY line, then append the new one
grep -v '^LLAMA_API_KEY=' "$ENV_FILE" > "$ENV_FILE.tmp" || true
echo "LLAMA_API_KEY=$LLAMA_API_KEY" >> "$ENV_FILE.tmp"
mv "$ENV_FILE.tmp" "$ENV_FILE"
chmod 0600 "$ENV_FILE"
ok "Wrote LLAMA_API_KEY to $ENV_FILE"

# ── systemd unit ─────────────────────────────────────────────────────

sudo tee /etc/systemd/system/frpc.service > /dev/null <<EOF
[Unit]
Description=frp client (OpenMono.ai inference-box side)
After=network.target docker.service
Wants=docker.service

[Service]
Type=simple
ExecStart=/usr/local/bin/frpc -c /etc/frp/frpc.toml
Restart=on-failure
RestartSec=10s

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now frpc
sleep 2

if systemctl is-active --quiet frpc; then
    ok "frpc is running and connected to $FRPS_ADDRESS:$FRPS_PORT"
else
    err "frpc failed to start. Check: sudo journalctl -u frpc"
    err "Common causes: wrong relayToken, revoked token, banned user,"
    err "                relay unreachable, firewall blocking outbound :$FRPS_PORT"
    exit 1
fi

# ── Restart llama-server so it picks up the new API key ──────────────

if command -v docker &>/dev/null && docker compose version &>/dev/null 2>&1; then
    if (cd "$REPO_DIR/docker" && docker compose ps --services 2>/dev/null | grep -q '^llama-server$'); then
        info "Restarting llama-server with new API key..."
        (cd "$REPO_DIR/docker" && docker compose restart llama-server) || \
            warn "Restart failed — run manually: cd docker && docker compose restart llama-server"
    else
        info "llama-server not running yet. Start it with: openmono start"
    fi
else
    warn "docker compose not found. Start llama-server manually after installing Docker."
fi

# ── Report ───────────────────────────────────────────────────────────

cat <<EOF

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${GREEN}✓ frp client connected to $FRPS_ADDRESS:$FRPS_PORT${NC}
${GREEN}✓ LLAMA_API_KEY stored in docker/.env${NC}
${GREEN}✓ Public endpoint: http://$FRPS_ADDRESS:$REMOTE_PORT${NC}

${BLUE}ON THE AGENT BOX, run:${NC}

  openmono config set llm.endpoint  http://$FRPS_ADDRESS:$REMOTE_PORT
  openmono config set llm.api_key   $LLAMA_API_KEY

Then:  openmono agent

${YELLOW}To check tunnel status:${NC}  sudo systemctl status frpc
${YELLOW}To tail tunnel logs:${NC}      sudo journalctl -u frpc -f
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
