#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────
# OpenMono.ai — Set up frps (self-hosted relay) for closed networks
# Runs on a machine that will act as the relay server on a closed network.
#
# Usage: openmono frps setup
# ─────────────────────────────────────────────────────────────────────

FRP_VERSION="${FRP_VERSION:-0.61.0}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
FRPS_PORT="${FRPS_PORT:-7000}"

RED=$'\033[0;31m'
GREEN=$'\033[0;32m'
YELLOW=$'\033[1;33m'
BLUE=$'\033[38;2;163;255;102m'
NC=$'\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── Prerequisite checks ──────────────────────────────────────────────

if [[ $EUID -ne 0 ]] && ! command -v sudo &>/dev/null; then
    err "Must run as root or have sudo installed."
    exit 1
fi

for cmd in curl tar openssl jq systemctl; do
    if ! command -v "$cmd" &>/dev/null; then
        err "Missing required command: $cmd"
        exit 1
    fi
done

# ── Detect architecture ──────────────────────────────────────────────

case "$(uname -m)" in
    aarch64) ARCH="arm64" ;;
    x86_64)  ARCH="amd64" ;;
    *) err "Unsupported architecture: $(uname -m)"; exit 1 ;;
esac

info "Detected architecture: linux_$ARCH"

# ── Generate relay token ────────────────────────────────────────────

RELAY_TOKEN="omr_local_$(openssl rand -hex 16)"
info "Generated relay token: $RELAY_TOKEN"

# ── Download and install frps ──────────────────────────────────────

TMP="$(mktemp -d)"
trap "rm -rf $TMP" EXIT

info "Downloading frp v$FRP_VERSION..."
if ! curl -fL \
    "https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/frp_${FRP_VERSION}_linux_${ARCH}.tar.gz" \
    -o "$TMP/frp.tar.gz"; then
    err "Failed to download frp. Check your internet connection or set FRP_VERSION to a cached version."
    exit 1
fi

tar xz -C "$TMP" --strip-components=1 -f "$TMP/frp.tar.gz"
sudo install -m 0755 "$TMP/frps" /usr/local/bin/frps
ok "Installed /usr/local/bin/frps"

# ── Write frps.toml ────────────────────────────────────────────────

sudo mkdir -p /etc/frp
sudo tee /etc/frp/frps.toml > /dev/null <<EOF
# frp server — OpenMono.ai local relay server
# Generated by openmono frps setup on $(date -u +%Y-%m-%dT%H:%M:%SZ)

bindPort = $FRPS_PORT
auth.token = "$RELAY_TOKEN"

# Optional: web dashboard
# webServer.addr = "0.0.0.0"
# webServer.port = 7500

log.to = "console"
log.level = "info"
EOF
sudo chmod 0600 /etc/frp/frps.toml
ok "Wrote /etc/frp/frps.toml"

# ── Store credentials for client setup ──────────────────────────────

CRED_FILE="$HOME/.openmono/local-relay.json"
mkdir -p "$(dirname "$CRED_FILE")"
cat > "$CRED_FILE" <<EOF
{
  "relayToken": "$RELAY_TOKEN",
  "frpsPort": $FRPS_PORT,
  "frpsAddress": "<server-ip>",
  "setupDate": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF
chmod 0600 "$CRED_FILE"
ok "Credentials saved to $CRED_FILE"

# ── systemd unit ─────────────────────────────────────────────────────

sudo tee /etc/systemd/system/frps.service > /dev/null <<EOF
[Unit]
Description=frp server (OpenMono.ai local relay)
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/frps -c /etc/frp/frps.toml
Restart=on-failure
RestartSec=10s

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now frps
sleep 2

if systemctl is-active --quiet frps; then
    ok "frps is running on port $FRPS_PORT"
else
    err "frps failed to start. Check: sudo journalctl -u frps"
    exit 1
fi

# ── Get server IP addresses ─────────────────────────────────────────

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ok "Local frps relay is ready!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Get all IP addresses
echo -e "${BLUE}Server IP addresses:${NC}"
ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v '^127\.' | while read -r ip; do
    echo "  - $ip"
done

echo ""
echo -e "${BLUE}On the INFERENCE box, run:${NC}"
echo "  openmono tunnel setup --local --frps-address=<server-ip>"
echo ""
echo -e "${BLUE}Then on the AGENT box, configure:${NC}"
echo "  # Get the remote port from inference box after tunnel setup"
echo "  openmono config set llm.endpoint http://<server-ip>:<remote-port>"
echo "  openmono config set llm.api_key <llama-api-key>"
echo ""
echo -e "${YELLOW}Relay Token (for inference box):${NC}"
echo "  $RELAY_TOKEN"
echo ""
echo -e "${YELLOW}Credentials file:${NC} $CRED_FILE"
echo ""
echo -e "${YELLOW}To check status:${NC}  sudo systemctl status frps"
echo -e "${YELLOW}To view logs:${NC}   sudo journalctl -u frps -f"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
