#!/usr/bin/env bash
# create-files.sh — creates two workspace files for the file-scan playbook
set -euo pipefail

WORKSPACE="${OPENMONO_WORKSPACE:-.}"

NOTES_FILE="$WORKSPACE/NOTES.md"
TODO_FILE="$WORKSPACE/TODO.md"

# ── File 1: NOTES.md ──────────────────────────────────────────────────────────
cat > "$NOTES_FILE" <<EOF
# Notes

Generated by the file-scan playbook on $(date '+%Y-%m-%d %H:%M:%S').

Add any project notes here.
EOF

echo "Created: $NOTES_FILE"

# ── File 2: TODO.md ───────────────────────────────────────────────────────────
cat > "$TODO_FILE" <<EOF
# TODO

Generated by the file-scan playbook on $(date '+%Y-%m-%d %H:%M:%S').

- [ ] Review grep results from scan step
- [ ] Address any outstanding TODOs found in source
EOF

echo "Created: $TODO_FILE"
